#docker network create -d overlay --attachable traefik_default
#env $(cat .env | grep ^[A-Z] | xargs) docker stack deploy -c docker-compose.basic-auth.env.yml crypto
version: '3.3'
networks:
  traefik_default:
    driver: overlay
    external:
      name:  traefik_default
services:
  crypto:
    
    image: eshnil2000/crypto-trading
    hostname: crypto
    labels:
      - traefik.http.routers.crypto.rule=Host(`crypto.${MY_DOMAIN}`)
      - traefik.http.routers.crypto.service=crypto
      - traefik.http.services.crypto.loadbalancer.server.port=5000
      - traefik.docker.network=traefik_default
      # generate login password: echo $(htpasswd -nb dappsuni dappsuni) | sed -e s/\\$/\\$\\$/g
      # example output: dappsuni:$$apr1$$dWmZs0Kn$$XSxY0LjUB.u6PoS/AED3D/
      #LOADING FROM .env file: echo $(htpasswd -nb test test)
      - "traefik.http.routers.crypto.middlewares=test-auth"

      - "traefik.http.middlewares.test-auth.basicauth.users=${ADMIN_HASH}"
    environment:
      KAFKA_BROKER_URL1: kafka1:9091
      KAFKA_BROKER_URL2: kafka2:9092
      KAFKA_BROKER_URL3: kafka3:9093
      TRANSACTIONS_TOPIC: queueing.transactions
      
    networks:
      traefik_default: